#!/bin/sh

goodbye () {
	echo "Goodbye."
}

installDependencies () {
        echo "Installing dependencies..."
        apt-get -y install git
        apt-get -y install nginx
        apt-get -y install nodejs
        apt-get -y install mongodb
	echo "Dependencies installed!"
}

configureNginx () {
        echo "Configuring Nginx..."
        nginxRoot="./configurations/nginx"
        cp $nginxRoot/nginx.conf /etc/nginx/nginx.conf
        cp $nginxRoot/sites-enabled/* /etc/nginx/sites-enabled
        echo "Nginx configured!"
}

configureDependencies () {
	echo "Configuring dependencies..."
	configureNginx
	echo "Dependencies configured!"
}

buildDevelopmentMachine () {
	echo "Building a development machine..."
	echo "Preparing $1..."
	mkdir $1
	echo "Installing services..."
	cp ./services/* /etc/init.d
	installDependencies
	configureDependencies
}

buildProductionMachine () {
	echo "Building a production machine..."
	echo "Writing to $1..."
}

getHelp () {
	echo "Usage: build [-h] [-p | -d] [-t <targetDirectory>]"
	exit
}

if [ "$1" = "-h" ]; then
	getHelp
elif [ "$1" = "-d" ] && [ $2 = "-t"  ]; then
	buildDevelopmentMachine $3
elif [ "$1" = "-p" ] && [ $2 = "-t"  ]; then
	buildProductionMachine $3
else
	getHelp
fi
